#!/usr/bin/env python3

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import shutil
import logging
import argparse
from tempfile import NamedTemporaryFile

from geotk.args import base_parser
from geotk.common import color_log
from geotk.dxf2kicad import dxf2kicad



LOG = logging.getLogger("dxf2kicad")



def main():
    parser = argparse.ArgumentParser(
        parents=[base_parser()],
        description="""\
Convert paths in a DXF file to fragment of lines in Kicad format.""")

    parser.add_argument(
        "dxf",
        metavar="DXF",
        help="Path to DXF file.")
    parser.add_argument(
        "kicad",
        metavar="KICAD",
        nargs="?",
        help="Path to KICAD file.")

    args = parser.parse_args()

    level = (logging.ERROR, logging.WARNING, logging.INFO, logging.DEBUG)[
        max(0, min(3, 1 + args.verbose - args.quiet))]

    handler = logging.StreamHandler()
    for name in ("dxf2kicad", "dxf"):
        log = logging.getLogger(name)
        log.addHandler(handler)
        color_log(log)
        log.setLevel(level)


    def wrapper(out):
        with open(args.dxf, "r", encoding="utf-8") as dxf:
            dxf2kicad(
                out, dxf,
            )


    if args.kicad:
        with NamedTemporaryFile("w", encoding="utf=8", delete=False) as out:
            os.fchmod(out.fileno(), os.stat(args.dxf).st_mode)
            wrapper(out)
        shutil.move(out.name, args.kicad)
    else:
        wrapper(sys.stdout)



if __name__ == "__main__":
    main()
